# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77394f812d155946941c6e919090a057a310408e25fbf30062efcb46d6e875849bc872329fc5575add22da58306f0defe4050a3f25668fff5cb6afe1047bd9a5

test:
  secret_key_base: 134970ee98a8f1a13e50440d3d14d1d5ba69c9973ba983afca4adc44292a25c19392074178f4f01a4ce762c5ee6215345e55778c46896249566380e5035a563b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
